//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS_Recycling {
    
    
    public partial class WebFormCustomerRelationContacts {
        
        /// <summary>
        /// LabelPath control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelPath;
        
        /// <summary>
        /// WebUserControlCustomerRelationContactOverview1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TMS_Recycling.WebUserControlCustomerRelationContactOverview WebUserControlCustomerRelationContactOverview1;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new TMS_Recycling.SiteCustomerRelation Master {
            get {
                return ((TMS_Recycling.SiteCustomerRelation)(base.Master));
            }
        }
    }
}
